name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  pylint:
    name: Run Pylint
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/pylint.yml # Calls the Pylint workflow
    with: {}

  django_build_test:
    name: Django Build & Test
    permissions:
      contents: read
      pull-requests: write
    needs: pylint
    uses: ./.github/workflows/django.yml # Calls the Django workflow
    with: {}

  # codeql_analysis:
  #   name: CodeQL Analysis
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #   needs: django_build_test
  #   uses: ./.github/workflows/codeql.yml # Calls the CodeQL workflow
  #   with: {}

  # sonarcloud_analysis:
  #   name:  SonarCloud analysis
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #   needs: codeql_analysis
  #   uses: ./.github/workflows/sonarcloud.yml # Calls the sonarcloud workflow
  #   with: {}
