name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  pylint:
    name: Run Pylint
    uses: ./.github/workflows/pylint.yml # Calls the Pylint workflow
    with: {}

  django_build_test:
    name: Django Build & Test
    needs: pylint
    uses: ./.github/workflows/django.yml # Calls the Django workflow
    with: {}

  codeql_analysis:
    name: CodeQL Analysis
    needs: django_build_test
    uses: ./.github/workflows/codeql.yml # Calls the CodeQL workflow
    with: {}

  sonarcloud_analysis:
    name:  SonarCloud analysis
    needs: codeql_analysis
    uses: ./.github/workflows/sonarcloud.yml # Calls the sonarcloud workflow
    with: {}
